name: Markdown style checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run_style_checks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Look out for file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            target_files:
              - '**/*.md'
              - '.github/workflows/**'
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        if: steps.changes.outputs.target_files == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.changes.outputs.target_files == 'true'
        run: |
          python -m pip install pymarkdownlnt
      - name: Lint with pymarkdown
        if: steps.changes.outputs.target_files == 'true'
        run: |
          pymarkdown scan **/*.md
