name: Python tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 720
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Look out for file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            target_files:
              - '**/*.py'
              - '.github/workflows/**'
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        if: steps.changes.outputs.target_files == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.changes.outputs.target_files == 'true'
        run: |
          python -m pip install -e .[github]
      - name: Run tests with pytest
        if: steps.changes.outputs.target_files == 'true'
        run: |
          pytest -vv --suppress-no-test-exit-code
